[package]
name = "reflection-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
serde = "*"

[dev-dependencies]
criterion = { version = "0.5" }


[[bench]]
name = "main"
harness = false
