[package]
name = "lib"
version = "0.1.0"
edition = "2024"

[lib]
test = false

[dev-dependencies]
criterion = { version = "0.5", features = [] }

[dependencies]
serde_json = "1.0.145"
serde = { version = "*", features = ['derive'] }
nom = "*"

[[bench]]
name = "main"
harness = false
