name: "CI"
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: .

permissions:
  contents: write
  pull-requests: read

jobs:
  Changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      reflection: ${{ steps.filter.outputs.reflection }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            reflection:
              - '**/src/**'
              - '**/test/**'
              - '**/bench*/**'
              - '.github/**'
  Build:
    needs: changes
    if: ${{ needs.changes.outputs.reflection == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        ghc-version: [
            # 9.0.2,
            # 9.2.8,
            # 9.4.8,
            # 9.6.6,
            # 9.8.4,
            # 9.10.1,
            9.12.2,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Setup GHC
        uses: ./.github/actions/cache-deps
        with:
          ghc-version: ${{ matrix.ghc-version }}
      - name: Build
        run: |
          stack --compiler ghc-${{ matrix.ghc-version }} build \
            reflection-base:lib                                        \
            reflection-base:test:reflection-test                       \
            reflection-json-parser-benchmark-server:exe:haskell-server \
            reflection-json-parser:bench:micro                         \
            reflection-json-parser:lib                                 \
            reflection-json-parser:test:json-parser-test               \
            reflection-serialiser:bench:micro                          \
            reflection-serialiser:bench:pandoc                         \
            reflection-serialiser:bench:servant                        \
            reflection-serialiser:lib                                  \
            reflection-serialiser:test:serialiser-test                 \
            --no-run-benchmarks --no-run-tests
  Format:
    if: ${{ needs.changes.outputs.reflection == 'true' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-deps
      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.18.0.0"
          pattern: |
            **/*.hs
            !.stack-work/
          follow-symbolic-links: false
  Lint:
    if: ${{ needs.changes.outputs.reflection == 'true' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-deps
      - name: "Set up HLint"
        uses: rwe/actions-hlint-setup@v1
        with:
          version: "3.10"
      - name: "Run HLint"
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["reflection-base/src/", "reflection-json-parser/src/", "reflection-serialiser/src"]'
          fail-on: warning
  Tests:
    runs-on: ubuntu-latest
    needs: [Build]
    strategy:
      fail-fast: false
      matrix:
        ghc-version: [
            # 9.0.2,
            # 9.2.8,
            # 9.4.8,
            # 9.6.6,
            # 9.8.4,
            # 9.10.1,
            9.12.2,
          ]
    if: ${{ needs.changes.outputs.reflection == 'true' && always() }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup GHC
        uses: ./.github/actions/cache-deps
        with:
          ghc-version: ${{ matrix.ghc-version }}
      - name: Run unit tests
        run: stack test --compiler ghc-${{ matrix.ghc-version }}
